### PR TITLE
Dynamic color picker added to the footer

### PR DESCRIPTION
**Pull request by kyleatblackfoot**
Here we go mate, all done. Hope you like it

### CODE REVIEW

**Comment by nakulrathore** [comment]
@kyleatblackfoot Fantastic, this is what we were looking for.

there is one tiny thing i found, the picker does not toggle off when user clicks on any other preset bg color, if possible can you do it ?

**Comment by nakulrathore** [comment]
@all-contributors please add @kyleatblackfoot and @kylewetton for code

**Comment by kyleatblackfoot** [comment]
No worries let me sort this out

**Comment by kyleatblackfoot** [comment]
Hey I'm quite new to pull requests, I've done this update. Is there something extra that I need to do?

**Comment by kyleatblackfoot** [comment]
Hold fire on this, I've run into a bug

**Comment by kyleatblackfoot** [comment]
That's been fixed

**Pull request merged**
